# User-editable intervals (seconds only)
# ここだけ編集してください。main更新秒と各グループのskip_updatesを指定します。
main_update_interval_s: '5'
p00_skip_updates: '113'
p01_skip_updates: '0'
p02_skip_updates: '0'
p03_skip_updates: '65535'
p05_skip_updates: '119'
p07_skip_updates: '115'
p09_skip_updates: '139'
p10_skip_updates: '189'
