number:
  - platform: modbus_controller
    id: num_p03_57088
    modbus_controller_id: srne_main
    internal: true
    register_type: holding
    skip_updates: ${p03_skip_updates}
    force_new_range: true
    address: 57088
    value_type: U_WORD
    write_lambda: |-
      return (int) x;
  - platform: modbus_controller
    id: num_p03_57089
    modbus_controller_id: srne_main
    internal: true
    register_type: holding
    skip_updates: ${p03_skip_updates}
    force_new_range: true
    address: 57089
    value_type: U_WORD
    write_lambda: |-
      return (int) x;
  - platform: modbus_controller
    id: num_p03_57090
    modbus_controller_id: srne_main
    internal: true
    register_type: holding
    skip_updates: ${p03_skip_updates}
    force_new_range: true
    address: 57090
    value_type: U_WORD
    write_lambda: |-
      return (int) x;
  - platform: modbus_controller
    id: num_p03_57094
    modbus_controller_id: srne_main
    internal: true
    register_type: holding
    skip_updates: ${p03_skip_updates}
    force_new_range: true
    address: 57094
    value_type: U_DWORD
    write_lambda: |-
      return (int) x;
  - platform: modbus_controller
    id: num_p03_57101
    modbus_controller_id: srne_main
    internal: true
    register_type: holding
    skip_updates: ${p03_skip_updates}
    force_new_range: true
    address: 57101
    value_type: U_WORD
    write_lambda: |-
      return (int) x;

button:
  - platform: template
    name: "ON⁄OFF Control On"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57088
                  value: 1
  - platform: template
    name: "ON⁄OFF Control Off"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57088
                  value: 0
  - platform: template
    name: "Device Reset"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57089
                  value: 1
  - platform: template
    name: "Restore Factory Defaults"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57090
                  value: 170
  - platform: template
    name: "Clear Power Statistics"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57090
                  value: 187
  - platform: template
    name: "Clear Fault History"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57090
                  value: 204
  - platform: template
    name: "Firmware Upgrade Command"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57094
                  value: 1
  - platform: template
    name: "Immediate Equalization Charge Command enabled"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57101
                  value: 1
  - platform: template
    name: "Immediate Equalization Charge Command disabled"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - number.set:
                  id: num_p03_57101
                  value: 0

globals:
  - id: p03_write_actions_enabled
    type: bool
    restore_value: no
    initial_value: 'false'

interval:
  - interval: 1s
    then:
      - lambda: |-
          if (!id(p03_write_actions_enabled) && millis() > 3000U) id(p03_write_actions_enabled) = true;
