button:
  - platform: template
    name: "ON⁄OFF Control On"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57088, 1));
  - platform: template
    name: "ON⁄OFF Control Off"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57088, 0));
  - platform: template
    name: "Device Reset"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57089, 1));
  - platform: template
    name: "Restore Factory Defaults"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57090, 170));
  - platform: template
    name: "Clear Power Statistics"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57090, 187));
  - platform: template
    name: "Clear Fault History"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57090, 204));
  - platform: template
    name: "Firmware Upgrade Command"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57094, 1));
  - platform: template
    name: "Immediate Equalization Charge Command enabled"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57101, 1));
  - platform: template
    name: "Immediate Equalization Charge Command disabled"
    entity_category: config
    internal: true
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(p03_write_actions_enabled);'
            then:
              - lambda: |-
                  auto controller = id(srne_main);
                  controller->queue_command(
                      esphome::modbus_controller::ModbusCommandItem::create_write_single_command(
                          controller, 57101, 0));

globals:
  - id: p03_write_actions_enabled
    type: bool
    restore_value: no
    initial_value: 'false'

interval:
  - interval: 1s
    then:
      - lambda: |-
          if (!id(p03_write_actions_enabled) && millis() > 3000U) id(p03_write_actions_enabled) = true;
